#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -euf -o pipefail

# sets an absolute path as the variable "my_dir" - this is set relative to where the file is located so is helpful e.g., if running from a different location
my_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

"${my_dir}/bash/install"
"${my_dir}/homebrew/install"
"${my_dir}/git/install"
"${my_dir}/ssh/install"
"${my_dir}/starship/install"
"${my_dir}/tmux/install"
"${my_dir}/R/install"

echo "All installation scripts completed successfully"
