#!/usr/bin/env bash
#
# Starship
#
# This installs Starship configuration

set -euf -o pipefail

my_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
dest_dir="${HOME}/.config"
dest_location="${dest_dir}/starship.toml"

echo -en "\e[36mInstalling custom Starship config...\e[39m "
rm -rf "${dest_location}"
mkdir -p "${dest_dir}"
ln -s "${my_dir}/starship.toml" "${dest_location}"
echo -e "\e[32mdone\e[39m"
